#!/bin/sh

set -e

IMAGE_NAME="nexus.bosa.belighted.com:8085/bosa"
TAG=${TAG:-"latest"}

runpath="$( cd "$(dirname "$0")" ; pwd -P )"
(cd ${runpath} &&
     docker build --file ${runpath}/Dockerfile --pull --tag $IMAGE_NAME:$TAG ../../.. &&
     docker push $IMAGE_NAME:$TAG)
