#!/bin/sh

set -e

IMAGE_NAME="nexus-server.devops-tools.svc.cluster.local:8085/bosa"
TAG=${TAG:-"latest"}

runpath="$( cd "$(dirname "$0")" ; pwd -P )"
#(cd ${runpath} &&
#     docker build --file ${runpath}/Dockerfile --pull --tag $IMAGE_NAME:$TAG ../../.. &&
#     docker push $IMAGE_NAME:$TAG)

(cd ${runpath} &&
     docker build --file ${runpath}/Dockerfile --pull --tag $IMAGE_NAME:$TAG ../../.. )
