#!/bin/sh

set -e

export DOCKER_BUILDKIT=1

IMAGE_NAME="bosa-base"
TAG=${TAG:-"latest"}

runpath="$( cd "$(dirname "$0")" ; pwd -P )"
(cd ${runpath} &&
     docker build --file ${runpath}/Dockerfile --pull --tag $IMAGE_NAME:$TAG ../..)
